cache:
  mount:
    - root/.git
    - root/.ivy2

build:
  image: hseeberger/scala-sbt:latest

  commands:
    - cp -a root/.ivy2 $HOME/.ivy2
    - echo hello world
    - sbt compile
    - ls

cache:
  mount:
    - .git
    - .ivy2
