#cache:
#  mount:
#   - .ivy

Build:
  image: havanero/sbt-docker:latest
  #image: play-scala:1.0-SNAPSHOT

  commands:
    - ./entryPoint.sh clean test assembly -Dsbt.ivy.home=.ivy

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com