cache:
  mount:
    - .git
    - /drone/.ivy2

build:
  test:
    image: hseeberger/scala-sbt

    commands:
      - sbt packageBin -Dsbt.ivy.home=/drone/.ivy2
      - sbt run -Dsbt.ivy.home=/drone/.ivy2 -Dconfig.resource=dev.conf

