build:
  image: play-scala:1.0-SNAPSHOT
  image: quay.io/ukhomeofficedigital/scala-sbt:v0.1.3

  commands:
    - ./entryPoint.sh sbt compile

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com