cache:
  mount:
    - .git
    - .ivy2

build:
  image: hseeberger/scala-sbt:latest

  commands:
    - echo hello world
    - mkdir -p /root/.ivy2
    - sbt -Dsbt.ivy.home=/root/.ivy2
    - sbt compile
    - ls  .git
    - ls /root/.ivy2

