cache:
  mount:
    - .git
    - .ivy2

build:
  image: hseeberger/scala-sbt:latest

  commands:
    - date
    - mkdir -p .ivy2
    - sbt "set offline := true" compile
    - ls .git
    - ls .ivy2
    - date

