compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing
  build:
    image: havanero/sbt-docker:latest

  commands:
    - sbt test -Dconfig.resource=dev.conf

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com