compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing

  commands:
    - sh ls

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com