compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing

  build:
    image: hseeberger/scala-sbt

  commands:
    - sbt clean test

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com