cache:
  mount:
    - .git
    - /drone/.ivy2

build:
  test:
    image: hseeberger/scala-sbt

    commands:
      - sbt compile -Dsbt.ivy.home=/drone/.ivy2
      - sbt run -Dsbt.ivy.home=/drone/.ivy2
      - cd ActiviBMP2.0 && mvn clean install

