build:
  image: play-scala:1.0-SNAPSHOT

  commands:
    - "./build.sh publish"
    - "sbt -Ddocker:publishLocal"
    - "sbt ++2.11.8 compile"

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com