compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing

  commands:
    - sh "docker run play-scala:1.0-SNAPSHOT -Dconfig.resource=dev.conf"

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com