compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing

commands:
  - docker run -it --rm hseeberger/scala-sbt

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com