cache:
  mount:
    - .git
    - /drone/.ivy2

build:
  image: hseeberger/scala-sbt

  commands:
    - sbt assembly -Dsbt.ivy.home=/drone/.ivy2
    - sbt run -Dsbt.ivy.home=/drone/.ivy2 -Dconfig.resource=dev.conf

