cache:
  mount:
    - .git
    - /drone/.ivy2

build:
  image: hseeberger/scala-sbt

  commands:
    - sbt compile -Dsbt.ivy.home=/drone/.ivy2
    - sbt run -Dconfig.resources=dev.conf
    - sbt test

