cache:
  mount:
    - .git
    - .ivy2

build:
  image: hseeberger/scala-sbt:latest

  commands:
    - echo hello world
    - sbt compile
    - sbt docker:publishLocal
    - ls

cache:
  mount:
    - .git
    - .ivy2
