cache:
  mount:
    - /drone/.git
    - /drone/.ivy2

build:
  image: hseeberger/scala-sbt:latest

  commands:
    - date
    - sbt test -Dsbt.ivy.home=/drone/.ivy2
    - ls /drone/.git
    - ls /drone/.ivy2
    - date

