Build:
  #image: play-scala:1.0-SNAPSHOT

  image: havanero/sbt-docker:latest

  commands:
    - ./entryPoint.sh clean test assembly -Dsbt.ivy.home=/drone/.ivy

  notify:
    email:
      recipients:
        - caleb.carvalho@gmail.com